// Code generated by enterprise.
package models

import "github.com/MrSametBurgazoglu/enterprise/client"

import "github.com/google/uuid"
import "strings"

type AccountPredicate struct {
	where []*client.WhereList
}

func (t *AccountPredicate) Where(w ...client.PredicateI) {
	t.where = nil
	wl := &client.WhereList{}
	wl.Items = append(wl.Items, w...)
	t.where = append(t.where, wl)
}

func (t *AccountPredicate) ORWhere(w ...client.PredicateI) {
	wl := &client.WhereList{}
	wl.Items = append(wl.Items, w...)
	t.where = append(t.where, wl)
}

func (t *AccountPredicate) IsIDEqual(v uuid.UUID) *client.Where {
	return &client.Where{
		Type:     client.EQ,
		Name:     AccountTableIDField,
		HasValue: true,
		Value:    v,
	}
}

func (t *AccountPredicate) IsNameEqual(v string) *client.Where {
	return &client.Where{
		Type:     client.EQ,
		Name:     AccountTableNameField,
		HasValue: true,
		Value:    v,
	}
}

func (t *AccountPredicate) IsSurnameEqual(v string) *client.Where {
	return &client.Where{
		Type:     client.EQ,
		Name:     AccountTableSurnameField,
		HasValue: true,
		Value:    v,
	}
}

func (t *AccountPredicate) IsStatusEqual(v string) *client.Where {
	return &client.Where{
		Type:     client.EQ,
		Name:     AccountTableStatusField,
		HasValue: true,
		Value:    v,
	}
}

func (t *AccountPredicate) IsDenemeIDEqual(v uuid.UUID) *client.Where {
	return &client.Where{
		Type:     client.EQ,
		Name:     AccountTableDenemeIDField,
		HasValue: true,
		Value:    v,
	}
}

func (t *AccountPredicate) IsSerialEqual(v uint) *client.Where {
	return &client.Where{
		Type:     client.EQ,
		Name:     AccountTableSerialField,
		HasValue: true,
		Value:    v,
	}
}

func (t *AccountPredicate) IsIDNotEqual(v uuid.UUID) *client.Where {
	return &client.Where{
		Type:     client.NEQ,
		Name:     AccountTableIDField,
		HasValue: true,
		Value:    v,
	}
}

func (t *AccountPredicate) IsNameNotEqual(v string) *client.Where {
	return &client.Where{
		Type:     client.NEQ,
		Name:     AccountTableNameField,
		HasValue: true,
		Value:    v,
	}
}

func (t *AccountPredicate) IsSurnameNotEqual(v string) *client.Where {
	return &client.Where{
		Type:     client.NEQ,
		Name:     AccountTableSurnameField,
		HasValue: true,
		Value:    v,
	}
}

func (t *AccountPredicate) IsStatusNotEqual(v string) *client.Where {
	return &client.Where{
		Type:     client.NEQ,
		Name:     AccountTableStatusField,
		HasValue: true,
		Value:    v,
	}
}

func (t *AccountPredicate) IsDenemeIDNotEqual(v uuid.UUID) *client.Where {
	return &client.Where{
		Type:     client.NEQ,
		Name:     AccountTableDenemeIDField,
		HasValue: true,
		Value:    v,
	}
}

func (t *AccountPredicate) IsSerialNotEqual(v uint) *client.Where {
	return &client.Where{
		Type:     client.NEQ,
		Name:     AccountTableSerialField,
		HasValue: true,
		Value:    v,
	}
}

func (t *AccountPredicate) IsIDIN(v ...uuid.UUID) *client.Where {
	return &client.Where{
		Type:     client.ANY,
		Name:     AccountTableIDField,
		HasValue: true,
		Value:    v,
	}
}

func (t *AccountPredicate) IsNameIN(v ...string) *client.Where {
	return &client.Where{
		Type:     client.ANY,
		Name:     AccountTableNameField,
		HasValue: true,
		Value:    v,
	}
}

func (t *AccountPredicate) IsSurnameIN(v ...string) *client.Where {
	return &client.Where{
		Type:     client.ANY,
		Name:     AccountTableSurnameField,
		HasValue: true,
		Value:    v,
	}
}

func (t *AccountPredicate) IsStatusIN(v ...string) *client.Where {
	return &client.Where{
		Type:     client.ANY,
		Name:     AccountTableStatusField,
		HasValue: true,
		Value:    v,
	}
}

func (t *AccountPredicate) IsDenemeIDIN(v ...uuid.UUID) *client.Where {
	return &client.Where{
		Type:     client.ANY,
		Name:     AccountTableDenemeIDField,
		HasValue: true,
		Value:    v,
	}
}

func (t *AccountPredicate) IsSerialIN(v ...uint) *client.Where {
	return &client.Where{
		Type:     client.ANY,
		Name:     AccountTableSerialField,
		HasValue: true,
		Value:    v,
	}
}

func (t *AccountPredicate) IsIDNotIN(v ...uuid.UUID) *client.Where {
	return &client.Where{
		Type:     client.NANY,
		Name:     AccountTableIDField,
		HasValue: true,
		Value:    v,
	}
}

func (t *AccountPredicate) IsNameNotIN(v ...string) *client.Where {
	return &client.Where{
		Type:     client.NANY,
		Name:     AccountTableNameField,
		HasValue: true,
		Value:    v,
	}
}

func (t *AccountPredicate) IsSurnameNotIN(v ...string) *client.Where {
	return &client.Where{
		Type:     client.NANY,
		Name:     AccountTableSurnameField,
		HasValue: true,
		Value:    v,
	}
}

func (t *AccountPredicate) IsStatusNotIN(v ...string) *client.Where {
	return &client.Where{
		Type:     client.NANY,
		Name:     AccountTableStatusField,
		HasValue: true,
		Value:    v,
	}
}

func (t *AccountPredicate) IsDenemeIDNotIN(v ...uuid.UUID) *client.Where {
	return &client.Where{
		Type:     client.NANY,
		Name:     AccountTableDenemeIDField,
		HasValue: true,
		Value:    v,
	}
}

func (t *AccountPredicate) IsSerialNotIN(v ...uint) *client.Where {
	return &client.Where{
		Type:     client.NANY,
		Name:     AccountTableSerialField,
		HasValue: true,
		Value:    v,
	}
}

func (t *AccountPredicate) IsNameLike(v string) *client.Where {
	return &client.Where{
		Type:     client.LIKE,
		Name:     AccountTableNameField,
		HasValue: true,
		Value:    v,
	}
}

func (t *AccountPredicate) IsNameILike(v string) *client.Where {
	return &client.Where{
		Type:     client.ILIKE,
		Name:     AccountTableNameField,
		HasValue: true,
		Value:    v,
	}
}

func (t *AccountPredicate) IsSurnameLike(v string) *client.Where {
	return &client.Where{
		Type:     client.LIKE,
		Name:     AccountTableSurnameField,
		HasValue: true,
		Value:    v,
	}
}

func (t *AccountPredicate) IsSurnameILike(v string) *client.Where {
	return &client.Where{
		Type:     client.ILIKE,
		Name:     AccountTableSurnameField,
		HasValue: true,
		Value:    v,
	}
}

func (t *AccountPredicate) IsStatusLike(v string) *client.Where {
	return &client.Where{
		Type:     client.LIKE,
		Name:     AccountTableStatusField,
		HasValue: true,
		Value:    v,
	}
}

func (t *AccountPredicate) IsStatusILike(v string) *client.Where {
	return &client.Where{
		Type:     client.ILIKE,
		Name:     AccountTableStatusField,
		HasValue: true,
		Value:    v,
	}
}

func (t *AccountPredicate) IsDenemeIDNil() *client.Where {
	return &client.Where{
		Type: client.NIL,
		Name: AccountTableDenemeIDField,
	}
}

func (t *AccountPredicate) IsDenemeIDNotNil() *client.Where {
	return &client.Where{
		Type: client.NNIL,
		Name: AccountTableDenemeIDField,
	}
}

func (t *AccountPredicate) SerialGreaterThan(v uint) *client.Where {
	return &client.Where{
		Type:     client.GT,
		Name:     AccountTableSerialField,
		HasValue: true,
		Value:    v,
	}
}

func (t *AccountPredicate) SerialGreaterEqualThan(v uint) *client.Where {
	return &client.Where{
		Type:     client.GTE,
		Name:     AccountTableSerialField,
		HasValue: true,
		Value:    v,
	}
}

func (t *AccountPredicate) SerialLowerThan(v uint) *client.Where {
	return &client.Where{
		Type:     client.LT,
		Name:     AccountTableSerialField,
		HasValue: true,
		Value:    v,
	}
}

func (t *AccountPredicate) SerialLowerEqualThan(v uint) *client.Where {
	return &client.Where{
		Type:     client.LTE,
		Name:     AccountTableSerialField,
		HasValue: true,
		Value:    v,
	}
}

func (t *AccountPredicate) GetWhereInfoString() string {
	var whereString []string
	for _, list := range t.where {
		whereAnd := ""
		var whereAndString []string
		for _, item := range list.Items {
			whereAndString = append(whereAndString, item.GetName())
		}
		whereAnd = strings.Join(whereAndString, "_AND_")
		whereString = append(whereString, whereAnd)
	}
	return strings.Join(whereString, "__OR__")
}
