// Code generated by enterprise.
package models

import (
	"context"
	"fmt"
	"github.com/MrSametBurgazoglu/enterprise/client"
	"github.com/MrSametBurgazoglu/enterprise/logger"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgxpool"
	"log/slog"
	"os"
)

type Options struct {
	Url   string
	Debug bool
}

type IDatabase interface {
	NewTransaction(ctx context.Context, options ...pgx.TxOptions) (client.DatabaseTransactionClient, error)
	Transaction(ctx context.Context, fn func(tx client.DatabaseTransactionClient) error, options ...pgx.TxOptions) error
	Exit()
	client.DatabaseClient
}

type Database struct {
	pool    *pgxpool.Pool
	Options *Options
	Logger  logger.Logger
}

func (d *Database) Exec(ctx context.Context, sql string, arguments ...any) (commandTag pgconn.CommandTag, err error) {
	commandTag, err = d.pool.Exec(ctx, sql, arguments...)
	var namedArgs pgx.NamedArgs
	if len(arguments) > 0 {
		if na, ok := arguments[0].(pgx.NamedArgs); ok {
			namedArgs = na
		}
	}
	if err != nil {
		d.Logger.LogError(ctx, sql, namedArgs, err)
	} else if d.Options.Debug {
		d.Logger.Log(ctx, sql, namedArgs)
	}
	return commandTag, err
}

func (d *Database) Query(ctx context.Context, sql string, args ...any) (rows pgx.Rows, err error) {
	rows, err = d.pool.Query(ctx, sql, args...)
	var namedArgs pgx.NamedArgs
	if len(args) > 0 {
		if na, ok := args[0].(pgx.NamedArgs); ok {
			namedArgs = na
		}
	}
	if err != nil {
		d.Logger.LogError(ctx, sql, namedArgs, err)
	} else if d.Options.Debug {
		d.Logger.Log(ctx, sql, namedArgs)
	}
	return rows, err
}

func (d *Database) QueryRow(ctx context.Context, sql string, args ...any) (row pgx.Row) {
	row = d.pool.QueryRow(ctx, sql, args...)
	var namedArgs pgx.NamedArgs
	if len(args) > 0 {
		if na, ok := args[0].(pgx.NamedArgs); ok {
			namedArgs = na
		}
	}
	if d.Options.Debug {
		d.Logger.Log(ctx, sql, namedArgs)
	}
	return row
}

func (d *Database) SetupPostgres(dbUrl string) error {
	var err error
	d.pool, err = pgxpool.New(context.Background(), dbUrl)
	if err != nil {
		return fmt.Errorf("Unable to create connection pool: %v\n", err)
	}
	return nil
}

func (d *Database) NewTransaction(ctx context.Context, options ...pgx.TxOptions) (client.DatabaseTransactionClient, error) {
	var (
		err error
		tx  pgx.Tx
	)

	if len(options) == 0 {
		tx, err = d.pool.Begin(ctx)
	} else {
		tx, err = d.pool.BeginTx(ctx, options[0])
	}

	if err != nil {
		return nil, err
	}

	return &Transaction{Tx: tx}, nil
}

func (d *Database) Transaction(ctx context.Context, fn func(tx client.DatabaseTransactionClient) error, options ...pgx.TxOptions) error {
	tx, err := d.NewTransaction(ctx, options...)
	if err != nil {
		return err
	}
	var shouldRollback bool = true
	defer func() {
		if p := recover(); p != nil {
			_ = tx.Rollback(ctx)
			panic(p)
		} else if shouldRollback {
			_ = tx.Rollback(ctx)
		}
	}()
	err = fn(tx)
	if err != nil {
		return err
	}
	shouldRollback = false
	return tx.Commit(ctx)
}

func (d *Database) Exit() {
	d.pool.Close()
}

type Transaction struct {
	Logger logger.Logger
	pgx.Tx
}

func (t Transaction) GetLogger() logger.Logger {
	return t.Logger
}

func NewDB(options *Options) (IDatabase, error) {
	d := &Database{Options: options}
	err := d.SetupPostgres(options.Url)
	slogger := initializeSlog(slog.LevelDebug)
	d.Logger = logger.NewLogger(slogger)
	return d, err
}

func initializeSlog(logLevel slog.Level) *slog.Logger {
	return slog.New(slog.NewJSONHandler(os.Stdout, &slog.HandlerOptions{Level: logLevel}))
}

type PredicateI = client.PredicateI

func Or(preds ...PredicateI) PredicateI {
	return client.Or(preds...)
}

func And(preds ...PredicateI) PredicateI {
	return client.And(preds...)
}
