// Code generated by enterprise.
package models

import "github.com/MrSametBurgazoglu/enterprise/client"

import "github.com/google/uuid"
import "strings"

type DenemePredicate struct {
	where []*client.WhereList
}

func (t *DenemePredicate) Where(w ...client.PredicateI) {
	t.where = nil
	wl := &client.WhereList{}
	wl.Items = append(wl.Items, w...)
	t.where = append(t.where, wl)
}

func (t *DenemePredicate) ORWhere(w ...client.PredicateI) {
	wl := &client.WhereList{}
	wl.Items = append(wl.Items, w...)
	t.where = append(t.where, wl)
}

func (t *DenemePredicate) WhereIf(cond bool, w client.PredicateI) *DenemePredicate {
	if cond {
		if len(t.where) == 0 {
			t.where = append(t.where, &client.WhereList{})
		}
		t.where[0].Items = append(t.where[0].Items, w)
	}
	return t
}

func (t *DenemePredicate) WhereIn(cond bool, w client.PredicateI) *DenemePredicate {
	if cond {
		if len(t.where) == 0 {
			t.where = append(t.where, &client.WhereList{})
		}
		t.where[0].Items = append(t.where[0].Items, w)
	}
	return t
}

func (t *DenemePredicate) IsIDEqual(v uuid.UUID) *client.Where {
	return &client.Where{
		Type:     client.EQ,
		Name:     DenemeTableIDField,
		HasValue: true,
		Value:    v,
	}
}

func (t *DenemePredicate) IsTestIDEqual(v uuid.UUID) *client.Where {
	return &client.Where{
		Type:     client.EQ,
		Name:     DenemeTableTestIDField,
		HasValue: true,
		Value:    v,
	}
}

func (t *DenemePredicate) IsCountEqual(v int) *client.Where {
	return &client.Where{
		Type:     client.EQ,
		Name:     DenemeTableCountField,
		HasValue: true,
		Value:    v,
	}
}

func (t *DenemePredicate) IsIsActiveEqual(v bool) *client.Where {
	return &client.Where{
		Type:     client.EQ,
		Name:     DenemeTableIsActiveField,
		HasValue: true,
		Value:    v,
	}
}

func (t *DenemePredicate) IsDenemeTypeEqual(v DenemeType) *client.Where {
	return &client.Where{
		Type:     client.EQ,
		Name:     DenemeTableDenemeTypeField,
		HasValue: true,
		Value:    v,
	}
}

func (t *DenemePredicate) IsIDNotEqual(v uuid.UUID) *client.Where {
	return &client.Where{
		Type:     client.NEQ,
		Name:     DenemeTableIDField,
		HasValue: true,
		Value:    v,
	}
}

func (t *DenemePredicate) IsTestIDNotEqual(v uuid.UUID) *client.Where {
	return &client.Where{
		Type:     client.NEQ,
		Name:     DenemeTableTestIDField,
		HasValue: true,
		Value:    v,
	}
}

func (t *DenemePredicate) IsCountNotEqual(v int) *client.Where {
	return &client.Where{
		Type:     client.NEQ,
		Name:     DenemeTableCountField,
		HasValue: true,
		Value:    v,
	}
}

func (t *DenemePredicate) IsIsActiveNotEqual(v bool) *client.Where {
	return &client.Where{
		Type:     client.NEQ,
		Name:     DenemeTableIsActiveField,
		HasValue: true,
		Value:    v,
	}
}

func (t *DenemePredicate) IsDenemeTypeNotEqual(v DenemeType) *client.Where {
	return &client.Where{
		Type:     client.NEQ,
		Name:     DenemeTableDenemeTypeField,
		HasValue: true,
		Value:    v,
	}
}

func (t *DenemePredicate) IsIDIN(v ...uuid.UUID) *client.Where {
	return &client.Where{
		Type:     client.ANY,
		Name:     DenemeTableIDField,
		HasValue: true,
		Value:    v,
	}
}

func (t *DenemePredicate) IsTestIDIN(v ...uuid.UUID) *client.Where {
	return &client.Where{
		Type:     client.ANY,
		Name:     DenemeTableTestIDField,
		HasValue: true,
		Value:    v,
	}
}

func (t *DenemePredicate) IsCountIN(v ...int) *client.Where {
	return &client.Where{
		Type:     client.ANY,
		Name:     DenemeTableCountField,
		HasValue: true,
		Value:    v,
	}
}

func (t *DenemePredicate) IsIsActiveIN(v ...bool) *client.Where {
	return &client.Where{
		Type:     client.ANY,
		Name:     DenemeTableIsActiveField,
		HasValue: true,
		Value:    v,
	}
}

func (t *DenemePredicate) IsDenemeTypeIN(v ...DenemeType) *client.Where {
	return &client.Where{
		Type:     client.ANY,
		Name:     DenemeTableDenemeTypeField,
		HasValue: true,
		Value:    v,
	}
}

func (t *DenemePredicate) IsIDNotIN(v ...uuid.UUID) *client.Where {
	return &client.Where{
		Type:     client.NANY,
		Name:     DenemeTableIDField,
		HasValue: true,
		Value:    v,
	}
}

func (t *DenemePredicate) IsTestIDNotIN(v ...uuid.UUID) *client.Where {
	return &client.Where{
		Type:     client.NANY,
		Name:     DenemeTableTestIDField,
		HasValue: true,
		Value:    v,
	}
}

func (t *DenemePredicate) IsCountNotIN(v ...int) *client.Where {
	return &client.Where{
		Type:     client.NANY,
		Name:     DenemeTableCountField,
		HasValue: true,
		Value:    v,
	}
}

func (t *DenemePredicate) IsIsActiveNotIN(v ...bool) *client.Where {
	return &client.Where{
		Type:     client.NANY,
		Name:     DenemeTableIsActiveField,
		HasValue: true,
		Value:    v,
	}
}

func (t *DenemePredicate) IsDenemeTypeNotIN(v ...DenemeType) *client.Where {
	return &client.Where{
		Type:     client.NANY,
		Name:     DenemeTableDenemeTypeField,
		HasValue: true,
		Value:    v,
	}
}

func (t *DenemePredicate) IsIDLike(v string) *client.Where {
	return &client.Where{
		Type:     client.LIKE,
		Name:     DenemeTableIDField,
		Cast:     "text",
		HasValue: true,
		Value:    v,
	}
}

func (t *DenemePredicate) IsIDILike(v string) *client.Where {
	return &client.Where{
		Type:     client.ILIKE,
		Name:     DenemeTableIDField,
		Cast:     "text",
		HasValue: true,
		Value:    v,
	}
}

func (t *DenemePredicate) IsTestIDLike(v string) *client.Where {
	return &client.Where{
		Type:     client.LIKE,
		Name:     DenemeTableTestIDField,
		Cast:     "text",
		HasValue: true,
		Value:    v,
	}
}

func (t *DenemePredicate) IsTestIDILike(v string) *client.Where {
	return &client.Where{
		Type:     client.ILIKE,
		Name:     DenemeTableTestIDField,
		Cast:     "text",
		HasValue: true,
		Value:    v,
	}
}

func (t *DenemePredicate) IsTestIDNil() *client.Where {
	return &client.Where{
		Type: client.NIL,
		Name: DenemeTableTestIDField,
	}
}

func (t *DenemePredicate) IsTestIDNotNil() *client.Where {
	return &client.Where{
		Type: client.NNIL,
		Name: DenemeTableTestIDField,
	}
}

func (t *DenemePredicate) CountGreaterThan(v int) *client.Where {
	return &client.Where{
		Type:     client.GT,
		Name:     DenemeTableCountField,
		HasValue: true,
		Value:    v,
	}
}

func (t *DenemePredicate) CountGreaterEqualThan(v int) *client.Where {
	return &client.Where{
		Type:     client.GTE,
		Name:     DenemeTableCountField,
		HasValue: true,
		Value:    v,
	}
}

func (t *DenemePredicate) CountLowerThan(v int) *client.Where {
	return &client.Where{
		Type:     client.LT,
		Name:     DenemeTableCountField,
		HasValue: true,
		Value:    v,
	}
}

func (t *DenemePredicate) CountLowerEqualThan(v int) *client.Where {
	return &client.Where{
		Type:     client.LTE,
		Name:     DenemeTableCountField,
		HasValue: true,
		Value:    v,
	}
}

func (t *DenemePredicate) GetWhereInfoString() string {
	var whereString []string
	for _, list := range t.where {
		whereAnd := ""
		var whereAndString []string
		for _, item := range list.Items {
			whereAndString = append(whereAndString, item.GetName())
		}
		whereAnd = strings.Join(whereAndString, "_AND_")
		whereString = append(whereString, whereAnd)
	}
	return strings.Join(whereString, "__OR__")
}
