// Code generated by enterprise.
package models

import (
	"context"
	"iter"

	"github.com/MrSametBurgazoglu/enterprise/client"
	"slices"

	"github.com/google/uuid"
)

const GroupTableName = "group"

const (
	GroupTableIDField      string = "id"
	GroupTableNameField    string = "name"
	GroupTableSurnameField string = "surname"
	GroupTableDataField    string = "data"
)

var databaseGroupOperationHook = func(ctx context.Context, operationInfo *client.OperationInfo, model *Group, operationFunc func() error) error {
	return operationFunc()
}

var databaseGroupListOperationHook = func(ctx context.Context, operationInfo *client.OperationInfo, model *GroupList, operationFunc func() error) error {
	return operationFunc()
}

func SetDatabaseGroupOperationHook(f func(ctx context.Context, operationInfo *client.OperationInfo, model *Group, operationFunc func() error) error) {
	databaseGroupOperationHook = f
}

func SetDatabaseGroupListOperationHook(f func(ctx context.Context, operationInfo *client.OperationInfo, model *GroupList, operationFunc func() error) error) {
	databaseGroupListOperationHook = f
}

func NewGroup(ctx context.Context, dc client.DatabaseClient) *Group {
	v := &Group{client: client.NewClient(dc), ctx: ctx}
	v.relations = new(client.RelationList)
	v.relations.RelationMap = make(map[string]*client.Relation)
	v.changedFields = make(map[string]any)
	v.result.Init()
	return v
}

func NewRelationGroup(ctx context.Context, dc client.DatabaseClient) *Group {
	v := &Group{client: client.NewClient(dc), ctx: ctx}
	v.relations = new(client.RelationList)
	v.relations.RelationMap = make(map[string]*client.Relation)
	v.changedFields = make(map[string]any)
	v.result.Init()
	return v
}

type Group struct {
	id uuid.UUID

	name string

	surname string

	data map[string]any

	changedFields     map[string]any
	changedFieldsList []string
	serialFields      []*client.SelectedField

	ctx    context.Context
	client *client.Client
	GroupPredicate
	relations *client.RelationList

	AccountList *AccountList

	result GroupResult
}

func (t *Group) GetDBName() string {
	return GroupTableName
}

func (t *Group) GetSelector() *GroupResult {
	t.result.selectedFields = nil
	t.result.SelectID()
	return &t.result
}

func (t *Group) GetRelationList() *client.RelationList {
	return t.relations
}

func (t *Group) IsExist() bool {
	var v uuid.UUID
	return t.id != v
}

func (t *Group) GetPrimaryKey() uuid.UUID {
	return t.id
}

func (t *Group) SetClient(client *client.Client) {
	t.client = client
}

func NewGroupList(ctx context.Context, dc client.DatabaseClient) *GroupList {
	v := &GroupList{client: client.NewClient(dc), ctx: ctx}
	v.relations = new(client.RelationList)
	v.relations.RelationMap = make(map[string]*client.Relation)
	v.result.Init()
	return v
}

func NewRelationGroupList(ctx context.Context, dc client.DatabaseClient) *GroupList {
	v := &GroupList{client: client.NewClient(dc), ctx: ctx}
	v.relations = new(client.RelationList)
	v.relations.RelationMap = make(map[string]*client.Relation)
	v.result.Init()
	return v
}

type GroupList struct {
	Items []*Group

	ctx    context.Context
	client *client.Client
	GroupPredicate
	order     []*client.Order
	paging    *client.Paging
	relations *client.RelationList
	result    GroupResult
}

func (t *GroupList) GetDBName() string {
	return GroupTableName
}

func (t *GroupList) GetRelationList() *client.RelationList {
	return t.relations
}

func (t *GroupList) IsExist() bool {
	return t.Items[len(t.Items)-1].IsExist()
}

func (t *GroupList) SetClient(client *client.Client) {
	t.client = client
}

func (t *GroupList) GetSelector() *GroupResult {
	t.result.selectedFields = nil
	t.result.SelectID()
	return &t.result
}

func (t *GroupList) DistinctString(field string) ([]string, error) {
	return t.client.DistinctString(t.ctx, t.where, t, field, t.order, t.paging)
}

func (t *GroupList) Count() (int, error) {
	return t.client.Count(t.ctx, t.where, t)
}

func (t *GroupList) MinName() (string, error) {
	var val string
	a := new(client.Aggregate)
	a.Min(GroupTableNameField, &val)
	scanFunc, err := t.client.Aggregate(t.ctx, t.where, t, a)
	if err != nil {
		return val, err
	}
	err = scanFunc()
	return val, err
}

func (t *GroupList) MaxName() (string, error) {
	var val string
	a := new(client.Aggregate)
	a.Max(GroupTableNameField, &val)
	scanFunc, err := t.client.Aggregate(t.ctx, t.where, t, a)
	if err != nil {
		return val, err
	}
	err = scanFunc()
	return val, err
}

func (t *GroupList) MinSurname() (string, error) {
	var val string
	a := new(client.Aggregate)
	a.Min(GroupTableSurnameField, &val)
	scanFunc, err := t.client.Aggregate(t.ctx, t.where, t, a)
	if err != nil {
		return val, err
	}
	err = scanFunc()
	return val, err
}

func (t *GroupList) MaxSurname() (string, error) {
	var val string
	a := new(client.Aggregate)
	a.Max(GroupTableSurnameField, &val)
	scanFunc, err := t.client.Aggregate(t.ctx, t.where, t, a)
	if err != nil {
		return val, err
	}
	err = scanFunc()
	return val, err
}

func (t *GroupList) SumName() (string, error) {
	var val string
	a := new(client.Aggregate)
	a.SumCast(GroupTableNameField, "numeric", &val)
	scanFunc, err := t.client.Aggregate(t.ctx, t.where, t, a)
	if err != nil {
		return val, err
	}
	err = scanFunc()
	return val, err
}

func (t *GroupList) AvgName() (float64, error) {
	var val float64
	a := new(client.Aggregate)
	a.AvgCast(GroupTableNameField, "numeric", &val)
	scanFunc, err := t.client.Aggregate(t.ctx, t.where, t, a)
	if err != nil {
		return val, err
	}
	err = scanFunc()
	return val, err
}

func (t *GroupList) SumSurname() (string, error) {
	var val string
	a := new(client.Aggregate)
	a.SumCast(GroupTableSurnameField, "numeric", &val)
	scanFunc, err := t.client.Aggregate(t.ctx, t.where, t, a)
	if err != nil {
		return val, err
	}
	err = scanFunc()
	return val, err
}

func (t *GroupList) AvgSurname() (float64, error) {
	var val float64
	a := new(client.Aggregate)
	a.AvgCast(GroupTableSurnameField, "numeric", &val)
	scanFunc, err := t.client.Aggregate(t.ctx, t.where, t, a)
	if err != nil {
		return val, err
	}
	err = scanFunc()
	return val, err
}

func (t *Group) SetID(v uuid.UUID) {
	t.id = v
	t.SetIDField()
}
func (t *Group) SetName(v string) {
	t.name = v
	t.SetNameField()
}
func (t *Group) SetSurname(v string) {
	t.surname = v
	t.SetSurnameField()
}
func (t *Group) SetData(v map[string]any) {
	t.data = v
	t.SetDataField()
}

func (t *Group) SetIDNillable(v *uuid.UUID) {
	if v == nil {
		return
	}
	t.SetID(*v)
}
func (t *Group) SetNameNillable(v *string) {
	if v == nil {
		return
	}
	t.SetName(*v)
}
func (t *Group) SetSurnameNillable(v *string) {
	if v == nil {
		return
	}
	t.SetSurname(*v)
}
func (t *Group) SetDataNillable(v *map[string]any) {
	if v == nil {
		return
	}
	t.SetData(*v)
}

func (t *Group) ParseID(v string) error {
	parsedID, err := uuid.Parse(v)
	if err != nil {
		return err
	}
	t.id = parsedID
	t.SetIDField()
	return nil
}

func (t *Group) GetIDAsString() string {

	return t.id.String()
}

func (t *Group) GetIDNillable() *uuid.UUID {
	return &t.id
}
func (t *Group) GetNameNillable() *string {
	return &t.name
}
func (t *Group) GetSurnameNillable() *string {
	return &t.surname
}
func (t *Group) GetDataNillable() *map[string]any {
	return &t.data
}

func (t *Group) NameIN(v ...string) bool {
	return slices.Contains(v, t.name)
}

func (t *Group) SurnameIN(v ...string) bool {
	return slices.Contains(v, t.surname)
}

func (t *Group) NameNotIN(v ...string) bool {
	return !slices.Contains(v, t.name)
}

func (t *Group) SurnameNotIN(v ...string) bool {
	return !slices.Contains(v, t.surname)
}

func (t *Group) GetID() uuid.UUID {
	return t.id
}

func (t *Group) GetName() string {
	return t.name
}

func (t *Group) GetSurname() string {
	return t.surname
}

func (t *Group) GetData() map[string]any {
	return t.data
}

func (t *Group) SetIDField() {
	if _, exist := t.changedFields[GroupTableIDField]; !exist {
		t.changedFields[GroupTableIDField] = t.id
		t.changedFieldsList = append(t.changedFieldsList, GroupTableIDField)
	}

}
func (t *Group) SetNameField() {
	if _, exist := t.changedFields[GroupTableNameField]; !exist {
		t.changedFields[GroupTableNameField] = t.name
		t.changedFieldsList = append(t.changedFieldsList, GroupTableNameField)
	}

}
func (t *Group) SetSurnameField() {
	if _, exist := t.changedFields[GroupTableSurnameField]; !exist {
		t.changedFields[GroupTableSurnameField] = t.surname
		t.changedFieldsList = append(t.changedFieldsList, GroupTableSurnameField)
	}

}
func (t *Group) SetDataField() {
	if _, exist := t.changedFields[GroupTableDataField]; !exist {
		t.changedFields[GroupTableDataField] = t.data
		t.changedFieldsList = append(t.changedFieldsList, GroupTableDataField)
	}

}

func (t *Group) WithAccountList(opts ...func(*AccountList)) *client.Relation {
	t.AccountList = NewRelationAccountList(t.ctx, t.client.Database)
	for _, opt := range opts {
		opt(t.AccountList)
	}
	t.result.Account = new(AccountResult)
	t.result.Account.Init()
	t.result.relations = append(t.result.relations, t.result.Account)
	t.result.relationsMap["account"] = t.result.Account
	for _, Relation := range t.AccountList.relations.Relations {
		t.result.Account.relations = append(t.result.Account.relations, Relation.RelationResult)
		t.result.Account.relationsMap[Relation.RelationTable] = Relation.RelationResult
	}
	r := &client.Relation{
		RelationModel:   t.AccountList,
		RelationTable:   "account",
		RelationResult:  t.result.Account,
		Where:           t.AccountList.where,
		ManyToManyTable: "account_group",
		RelationWhere: &client.RelationCondition{
			RelationValue:      "group_id",
			TableValue:         "account_id",
			RelationTableValue: "id",
		},
	}
	t.relations.Relations = append(t.relations.Relations, r)
	t.relations.RelationMap["account"] = r
	return r
}

func (t *GroupList) WithAccountList(opts ...func(*AccountList)) *client.Relation {
	v := NewRelationAccountList(t.ctx, t.client.Database)
	for _, opt := range opts {
		opt(v)
	}
	t.result.Account = new(AccountResult)
	t.result.Account.Init()
	t.result.relations = append(t.result.relations, t.result.Account)
	t.result.relationsMap["account"] = t.result.Account
	for _, Relation := range v.relations.Relations {
		t.result.Account.relations = append(t.result.Account.relations, Relation.RelationResult)
		t.result.Account.relationsMap[Relation.RelationTable] = Relation.RelationResult
	}
	r := &client.Relation{
		RelationModel:  v,
		RelationTable:  "account",
		RelationResult: t.result.Account,
		Where:          v.where,
		RelationWhere: &client.RelationCondition{
			RelationValue: "group_id",
			TableValue:    "account_id",
		},
	}
	t.relations.Relations = append(t.relations.Relations, r)
	t.relations.RelationMap["account"] = r
	return r
}

func (t *GroupList) cleanAccountList() {
	Relation := t.Items[len(t.Items)-1].relations
	p := 0
	for i, v := range Relation.Relations {
		if v.RelationTable == "account" {
			p = i
		}
	}
	Relation.Relations = append(Relation.Relations[:p], Relation.Relations[p+1:]...)
}

func (t *Group) GetChangedFields() map[string]any {
	return t.changedFields
}

func (t *Group) SetDefaults() {
	t.serialFields = nil

	if _, exist := t.changedFields[GroupTableIDField]; !exist {
		t.id = uuid.New()
		t.changedFields[GroupTableIDField] = t.id
		t.changedFieldsList = append(t.changedFieldsList, GroupTableIDField)
	}

}

func (t *Group) SetResult(result client.Result) {
	if t == nil {
		v := NewRelationGroup(t.ctx, t.client.Database)
		*t = *v
	}
	t.result = *result.(*GroupResult)
}

func (t *GroupList) SetResult(result client.Result) {
	if t == nil {
		v := NewRelationGroupList(t.ctx, t.client.Database)
		*t = *v
	}
	t.result = *result.(*GroupResult)
}

func (t *Group) ScanResult() {
	t.id = t.result.id
	t.name = t.result.name
	t.surname = t.result.surname
	t.data = t.result.data

	if _, ok := t.relations.RelationMap["account"]; ok {
		if t.AccountList == nil {
			t.AccountList = NewRelationAccountList(t.ctx, t.client.Database)
		}
		t.AccountList.relations = t.relations.RelationMap["account"].RelationModel.GetRelationList()
		t.AccountList.SetResult(t.result.relationsMap["account"])
		t.AccountList.ScanResult()
	}
}

func (t *Group) CheckPrimaryKey(v uuid.UUID) bool {
	return t.id == v
}

func (t *GroupList) ScanResult() {
	var v *Group
	if len(t.Items) == 0 {
		v = NewRelationGroup(t.ctx, t.client.Database)
		t.Items = append(t.Items, v)
	} else {
		for _, item := range t.Items {
			if item.CheckPrimaryKey(t.result.id) {
				v = item
				break
			}
		}
	}
	if v == nil {
		v = NewRelationGroup(t.ctx, t.client.Database)
		t.Items = append(t.Items, v)
	}
	v.result = t.result
	v.relations = t.relations
	v.ScanResult()
}

func (t *Group) GetContext() context.Context {
	return t.ctx
}

func (t *Group) WhereIf(cond bool, w client.PredicateI) *Group {
	t.GroupPredicate.WhereIf(cond, w)
	return t
}

func (t *Group) WhereIn(cond bool, w client.PredicateI) *Group {
	t.GroupPredicate.WhereIn(cond, w)
	return t
}

func (t *Group) WhereIfFn(cond bool, fn func() client.PredicateI) *Group {
	t.GroupPredicate.WhereIfFn(cond, fn)
	return t
}

func (t *Group) Select(fields ...string) *Group {
	t.result.selectedFields = nil
	for _, f := range fields {
		switch f {

		case GroupTableIDField:
			t.result.SelectID()

		case GroupTableNameField:
			t.result.SelectName()

		case GroupTableSurnameField:
			t.result.SelectSurname()

		case GroupTableDataField:
			t.result.SelectData()

		}
	}
	return t
}

func (t *Group) Get() error {
	return databaseGroupOperationHook(
		t.ctx,
		client.NewOperationInfo(
			GroupTableName,
			client.OperationTypeGet,
		),
		t,
		func() error {
			return t.client.Get(t.ctx, t.where, t, &t.result)
		},
	)
}

func (t *Group) Refresh() error {
	return databaseGroupOperationHook(
		t.ctx,
		client.NewOperationInfo(
			GroupTableName,
			client.OperationTypeRefresh,
		),
		t,
		func() error {
			return t.client.Refresh(t.ctx, t, &t.result, GroupTableIDField, t.id)
		},
	)
}

func (t *Group) Create() error {
	t.SetDefaults()
	return databaseGroupOperationHook(
		t.ctx,
		client.NewOperationInfo(
			GroupTableName,
			client.OperationTypeCreate,
		),
		t,
		func() error {
			return t.client.Create(t.ctx, GroupTableName, t.changedFields, t.changedFieldsList, t.serialFields)
		},
	)
}

func (t *Group) Update() error {
	return databaseGroupOperationHook(
		t.ctx,
		client.NewOperationInfo(
			GroupTableName,
			client.OperationTypeUpdate,
		),
		t,
		func() error {
			return t.client.Update(t.ctx, GroupTableName, t.changedFields, t.changedFieldsList, GroupTableIDField, t.id)
		},
	)
}

func (t *Group) Delete() error {
	return databaseGroupOperationHook(
		t.ctx,
		client.NewOperationInfo(
			GroupTableName,
			client.OperationTypeDelete,
		),
		t,
		func() error {
			return t.client.Delete(t.ctx, GroupTableName, GroupTableIDField, t.id)
		},
	)
}

func (t *GroupList) List() error {
	return databaseGroupListOperationHook(
		t.ctx,
		client.NewOperationInfo(
			GroupTableName,
			client.OperationTypeList,
		),
		t,
		func() error {
			return t.client.List(t.ctx, t.where, t, &t.result, t.order, t.paging)
		},
	)
}

func (t *GroupList) ListWithTotal(skip, limit int) (int, error) {
	total, err := t.Count()
	if err != nil {
		return 0, err
	}
	t.Paging(skip, limit)
	err = t.List()
	if err != nil {
		return 0, err
	}
	return total, nil
}

func (t *GroupList) WhereIf(cond bool, w client.PredicateI) *GroupList {
	t.GroupPredicate.WhereIf(cond, w)
	return t
}

func (t *GroupList) WhereIn(cond bool, w client.PredicateI) *GroupList {
	t.GroupPredicate.WhereIn(cond, w)
	return t
}

func (t *GroupList) Aggregate(f func(aggregate *client.Aggregate)) (func() error, error) {
	a := new(client.Aggregate)
	f(a)
	return t.client.Aggregate(t.ctx, t.where, t, a)
}

func (t *GroupList) AggregateRows(f func(aggregate *client.Aggregate)) (func() error, func(), error) {
	a := new(client.Aggregate)
	f(a)
	return t.client.AggregateRows(t.ctx, t.where, t, a)
}

func (t *GroupList) Create(list ...*Group) error {
	return databaseGroupListOperationHook(
		t.ctx,
		client.NewOperationInfo(
			GroupTableName,
			client.OperationTypeBulkCreate,
		),
		t,
		func() error {
			var changedFieldsList []map[string]any
			var changedFieldsListList [][]string
			for _, item := range list {
				changedFieldsList = append(changedFieldsList, item.changedFields)
				changedFieldsListList = append(changedFieldsListList, item.changedFieldsList)
			}
			return t.client.BulkCreate(t.ctx, GroupTableName, changedFieldsList, changedFieldsListList)
		},
	)
}

func (t *GroupList) Update(list ...*Group) error {
	return databaseGroupListOperationHook(
		t.ctx,
		client.NewOperationInfo(
			GroupTableName,
			client.OperationTypeBulkUpdate,
		),
		t,
		func() error {
			var valueList []any
			for _, item := range list {
				valueList = append(valueList, item.id)
			}
			return t.client.BulkUpdate(t.ctx, GroupTableName, list[0].changedFields, list[0].changedFieldsList, GroupTableIDField, valueList)
		},
	)
}

func (t *GroupList) Delete(list ...*Group) error {
	return databaseGroupListOperationHook(
		t.ctx,
		client.NewOperationInfo(
			GroupTableName,
			client.OperationTypeBulkDelete,
		),
		t,
		func() error {
			var valueList []any
			for _, item := range list {
				valueList = append(valueList, item.id)
			}
			return t.client.BulkDelete(t.ctx, GroupTableName, GroupTableIDField, valueList)
		},
	)
}

func (t *GroupList) DeleteWhere() (int64, error) {
	var affected int64
	err := databaseGroupListOperationHook(
		t.ctx,
		client.NewOperationInfo(
			GroupTableName,
			client.OperationTypeBulkDelete,
		),
		t,
		func() error {
			var err error
			affected, err = t.client.DeleteWhere(t.ctx, GroupTableName, t.where, t, GroupTableIDField)
			return err
		},
	)
	return affected, err
}

func (t *GroupList) UpdateWhere(set map[string]any) (int64, error) {
	var affected int64
	err := databaseGroupListOperationHook(
		t.ctx,
		client.NewOperationInfo(
			GroupTableName,
			client.OperationTypeBulkUpdate,
		),
		t,
		func() error {
			var err error
			affected, err = t.client.UpdateWhere(t.ctx, GroupTableName, set, t.where, t, GroupTableIDField)
			return err
		},
	)
	return affected, err
}

func (t *GroupList) Order(field string) *GroupList {
	t.order = append(t.order, &client.Order{Field: field})
	return t
}

func (t *GroupList) OrderDesc(field string) *GroupList {
	t.order = append(t.order, &client.Order{Field: field, Desc: true})
	return t
}

func (t *GroupList) Paging(skip, limit int) *GroupList {
	t.paging = &client.Paging{Skip: skip, Limit: limit}
	return t
}

func (t *GroupList) WhereIfFn(cond bool, fn func() client.PredicateI) *GroupList {
	t.GroupPredicate.WhereIfFn(cond, fn)
	return t
}

func (t *GroupList) Select(fields ...string) *GroupList {
	t.result.selectedFields = nil
	for _, f := range fields {
		switch f {

		case GroupTableIDField:
			t.result.SelectID()

		case GroupTableNameField:
			t.result.SelectName()

		case GroupTableSurnameField:
			t.result.SelectSurname()

		case GroupTableDataField:
			t.result.SelectData()

		}
	}
	return t
}

func (t *GroupList) AggregateSeq(fn func(*client.Aggregate)) iter.Seq2[int, error] {
	a := new(client.Aggregate)
	fn(a)
	return t.client.AggregateRowsSeq(t.ctx, t.where, t, a)
}

func (t *GroupList) GetByIDs(ids ...uuid.UUID) ([]*Group, error) {
	if len(ids) == 0 {
		return nil, nil
	}
	t.Where(t.IsIDIN(ids...))
	if err := t.List(); err != nil {
		return nil, err
	}
	return t.Items, nil
}

func (t *GroupList) GetByIDsMap(ids ...uuid.UUID) (map[uuid.UUID]*Group, error) {
	items, err := t.GetByIDs(ids...)
	if err != nil {
		return nil, err
	}
	res := make(map[uuid.UUID]*Group, len(items))
	for _, item := range items {
		res[item.GetPrimaryKey()] = item
	}
	return res, nil
}

func (t *GroupList) SumExpr(expr string, cast string, val any) error {
	a := new(client.Aggregate)
	a.SumExpr(expr, cast, val)
	scanFunc, err := t.client.Aggregate(t.ctx, t.where, t, a)
	if err != nil {
		return err
	}
	return scanFunc()
}

func (t *GroupList) AvgExpr(expr string, cast string, val any) error {
	a := new(client.Aggregate)
	a.AvgExpr(expr, cast, val)
	scanFunc, err := t.client.Aggregate(t.ctx, t.where, t, a)
	if err != nil {
		return err
	}
	return scanFunc()
}

type GroupResult struct {
	id      uuid.UUID
	name    string
	surname string
	data    map[string]any

	selectedFields []*client.SelectedField

	Account *AccountResult

	relations    []client.Result
	relationsMap map[string]client.Result
}

func (t *GroupResult) Init() {
	t.selectedFields = []*client.SelectedField{}
	t.relationsMap = make(map[string]client.Result)
	t.prepare()
	t.SelectAll()
}

func (t *GroupResult) GetSelectedFields() []*client.SelectedField {
	return t.selectedFields
}

func (t *GroupResult) GetRelations() []client.Result {
	return t.relations
}

func (t *GroupResult) prepare() {

}

func (t *GroupResult) SelectID() {
	v := &client.SelectedField{Name: GroupTableIDField, Value: &t.id}
	t.selectedFields = append(t.selectedFields, v)
}

func (t *GroupResult) SelectName() {
	v := &client.SelectedField{Name: GroupTableNameField, Value: &t.name}
	t.selectedFields = append(t.selectedFields, v)
}

func (t *GroupResult) SelectSurname() {
	v := &client.SelectedField{Name: GroupTableSurnameField, Value: &t.surname}
	t.selectedFields = append(t.selectedFields, v)
}

func (t *GroupResult) SelectData() {
	v := &client.SelectedField{Name: GroupTableDataField, Value: &t.data}
	t.selectedFields = append(t.selectedFields, v)
}

func (t *GroupResult) GetDBName() string {
	return GroupTableName
}

func (t *GroupResult) SelectAll() {
	t.SelectID()
	t.SelectName()
	t.SelectSurname()
	t.SelectData()

}

func (t *GroupResult) IsExist() bool {
	if t == nil {
		return false
	}
	var v uuid.UUID
	return t.id != v
}

func (t *Group) AddIntoAccount(relationship *Account) error {
	return t.client.AddManyToManyRelation(t.ctx, "account_group", "group_id", "account_id", t.id, relationship.GetPrimaryKey())
}

func (t *Group) RemoveFromAccount(relationship *Account) error {
	return t.client.DeleteManyToManyRelation(t.ctx, "account_group", "group_id", "account_id", t.id, relationship.GetPrimaryKey())
}

func (t *Group) IsInAccount(relationship *Account) (bool, error) {
	return t.client.ExistManyToManyRelation(t.ctx, "account_group", "group_id", "account_id", t.id, relationship.GetPrimaryKey())
}
