// Code generated by enterprise.
package models

import "github.com/MrSametBurgazoglu/enterprise/client"

import "github.com/google/uuid"
import "strings"

type GroupPredicate struct {
	where []*client.WhereList
}

func (t *GroupPredicate) Where(w ...client.PredicateI) {
	t.where = nil
	wl := &client.WhereList{}
	wl.Items = append(wl.Items, w...)
	t.where = append(t.where, wl)
}

func (t *GroupPredicate) ORWhere(w ...client.PredicateI) {
	wl := &client.WhereList{}
	wl.Items = append(wl.Items, w...)
	t.where = append(t.where, wl)
}

func (t *GroupPredicate) IsIDEqual(v uuid.UUID) *client.Where {
	return &client.Where{
		Type:     client.EQ,
		Name:     GroupTableIDField,
		HasValue: true,
		Value:    v,
	}
}

func (t *GroupPredicate) IsNameEqual(v string) *client.Where {
	return &client.Where{
		Type:     client.EQ,
		Name:     GroupTableNameField,
		HasValue: true,
		Value:    v,
	}
}

func (t *GroupPredicate) IsSurnameEqual(v string) *client.Where {
	return &client.Where{
		Type:     client.EQ,
		Name:     GroupTableSurnameField,
		HasValue: true,
		Value:    v,
	}
}

func (t *GroupPredicate) IsDataEqual(v map[string]any) *client.Where {
	return &client.Where{
		Type:     client.EQ,
		Name:     GroupTableDataField,
		HasValue: true,
		Value:    v,
	}
}

func (t *GroupPredicate) IsIDNotEqual(v uuid.UUID) *client.Where {
	return &client.Where{
		Type:     client.NEQ,
		Name:     GroupTableIDField,
		HasValue: true,
		Value:    v,
	}
}

func (t *GroupPredicate) IsNameNotEqual(v string) *client.Where {
	return &client.Where{
		Type:     client.NEQ,
		Name:     GroupTableNameField,
		HasValue: true,
		Value:    v,
	}
}

func (t *GroupPredicate) IsSurnameNotEqual(v string) *client.Where {
	return &client.Where{
		Type:     client.NEQ,
		Name:     GroupTableSurnameField,
		HasValue: true,
		Value:    v,
	}
}

func (t *GroupPredicate) IsDataNotEqual(v map[string]any) *client.Where {
	return &client.Where{
		Type:     client.NEQ,
		Name:     GroupTableDataField,
		HasValue: true,
		Value:    v,
	}
}

func (t *GroupPredicate) IsIDIN(v ...uuid.UUID) *client.Where {
	return &client.Where{
		Type:     client.ANY,
		Name:     GroupTableIDField,
		HasValue: true,
		Value:    v,
	}
}

func (t *GroupPredicate) IsNameIN(v ...string) *client.Where {
	return &client.Where{
		Type:     client.ANY,
		Name:     GroupTableNameField,
		HasValue: true,
		Value:    v,
	}
}

func (t *GroupPredicate) IsSurnameIN(v ...string) *client.Where {
	return &client.Where{
		Type:     client.ANY,
		Name:     GroupTableSurnameField,
		HasValue: true,
		Value:    v,
	}
}

func (t *GroupPredicate) IsDataIN(v ...map[string]any) *client.Where {
	return &client.Where{
		Type:     client.ANY,
		Name:     GroupTableDataField,
		HasValue: true,
		Value:    v,
	}
}

func (t *GroupPredicate) IsIDNotIN(v ...uuid.UUID) *client.Where {
	return &client.Where{
		Type:     client.NANY,
		Name:     GroupTableIDField,
		HasValue: true,
		Value:    v,
	}
}

func (t *GroupPredicate) IsNameNotIN(v ...string) *client.Where {
	return &client.Where{
		Type:     client.NANY,
		Name:     GroupTableNameField,
		HasValue: true,
		Value:    v,
	}
}

func (t *GroupPredicate) IsSurnameNotIN(v ...string) *client.Where {
	return &client.Where{
		Type:     client.NANY,
		Name:     GroupTableSurnameField,
		HasValue: true,
		Value:    v,
	}
}

func (t *GroupPredicate) IsDataNotIN(v ...map[string]any) *client.Where {
	return &client.Where{
		Type:     client.NANY,
		Name:     GroupTableDataField,
		HasValue: true,
		Value:    v,
	}
}

func (t *GroupPredicate) GetWhereInfoString() string {
	var whereString []string
	for _, list := range t.where {
		whereAnd := ""
		var whereAndString []string
		for _, item := range list.Items {
			whereAndString = append(whereAndString, item.GetName())
		}
		whereAnd = strings.Join(whereAndString, "_AND_")
		whereString = append(whereString, whereAnd)
	}
	return strings.Join(whereString, "__OR__")
}
