// Code generated by enterprise.
package models

import (
	"context"

	"github.com/MrSametBurgazoglu/enterprise/client"
	"slices"

	"github.com/MrSametBurgazoglu/enterprise/tests/custom_data_type"
	"github.com/google/uuid"
	"time"
)

const TestTableName = "test"

const (
	TestTableIDField        string = "id"
	TestTableNameField      string = "name"
	TestTableCreatedAtField string = "created_at"
	TestTableInfoField      string = "info"
	TestTableTypeField      string = "type"
	TestTableMetadataField  string = "metadata"
)

var databaseTestOperationHook = func(ctx context.Context, operationInfo *client.OperationInfo, model *Test, operationFunc func() error) error {
	return operationFunc()
}

var databaseTestListOperationHook = func(ctx context.Context, operationInfo *client.OperationInfo, model *TestList, operationFunc func() error) error {
	return operationFunc()
}

func SetDatabaseTestOperationHook(f func(ctx context.Context, operationInfo *client.OperationInfo, model *Test, operationFunc func() error) error) {
	databaseTestOperationHook = f
}

func SetDatabaseTestListOperationHook(f func(ctx context.Context, operationInfo *client.OperationInfo, model *TestList, operationFunc func() error) error) {
	databaseTestListOperationHook = f
}

func NewTest(ctx context.Context, dc client.DatabaseClient) *Test {
	v := &Test{client: client.NewClient(dc), ctx: ctx}
	v.relations = new(client.RelationList)
	v.relations.RelationMap = make(map[string]*client.Relation)
	v.changedFields = make(map[string]any)
	v.result.Init()
	return v
}

func NewRelationTest(ctx context.Context, dc client.DatabaseClient) *Test {
	v := &Test{client: client.NewClient(dc), ctx: ctx}
	v.relations = new(client.RelationList)
	v.relations.RelationMap = make(map[string]*client.Relation)
	v.changedFields = make(map[string]any)
	v.result.Init()
	return v
}

type Test struct {
	id uuid.UUID

	name string

	createdat time.Time

	info *custom_data_type.Custom

	type_ string

	metadata *map[string]any

	changedFields     map[string]any
	changedFieldsList []string
	serialFields      []*client.SelectedField

	ctx    context.Context
	client *client.Client
	TestPredicate
	relations *client.RelationList

	DenemeList *DenemeList

	result TestResult
}

func (t *Test) GetDBName() string {
	return TestTableName
}

func (t *Test) GetSelector() *TestResult {
	t.result.selectedFields = nil
	t.result.SelectID()
	return &t.result
}

func (t *Test) GetRelationList() *client.RelationList {
	return t.relations
}

func (t *Test) IsExist() bool {
	var v uuid.UUID
	return t.id != v
}

func (t *Test) GetPrimaryKey() uuid.UUID {
	return t.id
}

func (t *Test) SetClient(client *client.Client) {
	t.client = client
}

func NewTestList(ctx context.Context, dc client.DatabaseClient) *TestList {
	v := &TestList{client: client.NewClient(dc), ctx: ctx}
	v.relations = new(client.RelationList)
	v.relations.RelationMap = make(map[string]*client.Relation)
	v.result.Init()
	return v
}

func NewRelationTestList(ctx context.Context, dc client.DatabaseClient) *TestList {
	v := &TestList{client: client.NewClient(dc), ctx: ctx}
	v.relations = new(client.RelationList)
	v.relations.RelationMap = make(map[string]*client.Relation)
	v.result.Init()
	return v
}

type TestList struct {
	Items []*Test

	ctx    context.Context
	client *client.Client
	TestPredicate
	order     []*client.Order
	paging    *client.Paging
	relations *client.RelationList
	result    TestResult
}

func (t *TestList) GetDBName() string {
	return TestTableName
}

func (t *TestList) GetRelationList() *client.RelationList {
	return t.relations
}

func (t *TestList) IsExist() bool {
	return t.Items[len(t.Items)-1].IsExist()
}

func (t *TestList) SetClient(client *client.Client) {
	t.client = client
}

func (t *TestList) GetSelector() *TestResult {
	t.result.selectedFields = nil
	t.result.SelectID()
	return &t.result
}

func (t *TestList) DistinctString(field string) ([]string, error) {
	return t.client.DistinctString(t.ctx, t.where, t, field, t.order, t.paging)
}

func (t *TestList) Count() (int, error) {
	return t.client.Count(t.ctx, t.where, t)
}

func (t *TestList) MinName() (string, error) {
	var val string
	a := new(client.Aggregate)
	a.Min(TestTableNameField, &val)
	scanFunc, err := t.client.Aggregate(t.ctx, t.where, t, a)
	if err != nil {
		return val, err
	}
	err = scanFunc()
	return val, err
}

func (t *TestList) MaxName() (string, error) {
	var val string
	a := new(client.Aggregate)
	a.Max(TestTableNameField, &val)
	scanFunc, err := t.client.Aggregate(t.ctx, t.where, t, a)
	if err != nil {
		return val, err
	}
	err = scanFunc()
	return val, err
}

func (t *TestList) MinCreatedAt() (time.Time, error) {
	var val time.Time
	a := new(client.Aggregate)
	a.Min(TestTableCreatedAtField, &val)
	scanFunc, err := t.client.Aggregate(t.ctx, t.where, t, a)
	if err != nil {
		return val, err
	}
	err = scanFunc()
	return val, err
}

func (t *TestList) MaxCreatedAt() (time.Time, error) {
	var val time.Time
	a := new(client.Aggregate)
	a.Max(TestTableCreatedAtField, &val)
	scanFunc, err := t.client.Aggregate(t.ctx, t.where, t, a)
	if err != nil {
		return val, err
	}
	err = scanFunc()
	return val, err
}

func (t *TestList) MinType() (string, error) {
	var val string
	a := new(client.Aggregate)
	a.Min(TestTableTypeField, &val)
	scanFunc, err := t.client.Aggregate(t.ctx, t.where, t, a)
	if err != nil {
		return val, err
	}
	err = scanFunc()
	return val, err
}

func (t *TestList) MaxType() (string, error) {
	var val string
	a := new(client.Aggregate)
	a.Max(TestTableTypeField, &val)
	scanFunc, err := t.client.Aggregate(t.ctx, t.where, t, a)
	if err != nil {
		return val, err
	}
	err = scanFunc()
	return val, err
}

func (t *TestList) SumName() (string, error) {
	var val string
	a := new(client.Aggregate)
	a.SumCast(TestTableNameField, "numeric", &val)
	scanFunc, err := t.client.Aggregate(t.ctx, t.where, t, a)
	if err != nil {
		return val, err
	}
	err = scanFunc()
	return val, err
}

func (t *TestList) AvgName() (float64, error) {
	var val float64
	a := new(client.Aggregate)
	a.AvgCast(TestTableNameField, "numeric", &val)
	scanFunc, err := t.client.Aggregate(t.ctx, t.where, t, a)
	if err != nil {
		return val, err
	}
	err = scanFunc()
	return val, err
}

func (t *TestList) SumType() (string, error) {
	var val string
	a := new(client.Aggregate)
	a.SumCast(TestTableTypeField, "numeric", &val)
	scanFunc, err := t.client.Aggregate(t.ctx, t.where, t, a)
	if err != nil {
		return val, err
	}
	err = scanFunc()
	return val, err
}

func (t *TestList) AvgType() (float64, error) {
	var val float64
	a := new(client.Aggregate)
	a.AvgCast(TestTableTypeField, "numeric", &val)
	scanFunc, err := t.client.Aggregate(t.ctx, t.where, t, a)
	if err != nil {
		return val, err
	}
	err = scanFunc()
	return val, err
}

func (t *Test) SetID(v uuid.UUID) {
	t.id = v
	t.SetIDField()
}
func (t *Test) SetName(v string) {
	t.name = v
	t.SetNameField()
}
func (t *Test) SetCreatedAt(v time.Time) {
	t.createdat = v
	t.SetCreatedAtField()
}
func (t *Test) SetInfo(v *custom_data_type.Custom) {
	t.info = v
	t.SetInfoField()
}
func (t *Test) SetType(v string) {
	t.type_ = v
	t.SetTypeField()
}
func (t *Test) SetMetadata(v *map[string]any) {
	t.metadata = v
	t.SetMetadataField()
}

func (t *Test) SetInfoValue(v custom_data_type.Custom) {
	t.SetInfo(&v)
	t.SetInfoField()
}

func (t *Test) SetMetadataValue(v map[string]any) {
	t.SetMetadata(&v)
	t.SetMetadataField()
}

func (t *Test) SetIDNillable(v *uuid.UUID) {
	if v == nil {
		return
	}
	t.SetID(*v)
}
func (t *Test) SetNameNillable(v *string) {
	if v == nil {
		return
	}
	t.SetName(*v)
}
func (t *Test) SetCreatedAtNillable(v *time.Time) {
	if v == nil {
		return
	}
	t.SetCreatedAt(*v)
}

func (t *Test) SetTypeNillable(v *string) {
	if v == nil {
		return
	}
	t.SetType(*v)
}

func (t *Test) ParseID(v string) error {
	parsedID, err := uuid.Parse(v)
	if err != nil {
		return err
	}
	t.id = parsedID
	t.SetIDField()
	return nil
}

func (t *Test) GetIDAsString() string {

	return t.id.String()
}

func (t *Test) FormatCreatedAt(v string) string {

	return t.createdat.Format(v)
}

func (t *Test) ParseCreatedAt(layout, value string) error {
	parsedTime, err := time.Parse(layout, value)
	if err != nil {
		return err
	}
	t.createdat = parsedTime
	t.SetCreatedAtField()
	return nil
}

func (t *Test) GetIDNillable() *uuid.UUID {
	return &t.id
}
func (t *Test) GetNameNillable() *string {
	return &t.name
}
func (t *Test) GetCreatedAtNillable() *time.Time {
	return &t.createdat
}

func (t *Test) GetTypeNillable() *string {
	return &t.type_
}

func (t *Test) NameIN(v ...string) bool {
	return slices.Contains(v, t.name)
}

func (t *Test) TypeIN(v ...string) bool {
	return slices.Contains(v, t.type_)
}

func (t *Test) NameNotIN(v ...string) bool {
	return !slices.Contains(v, t.name)
}

func (t *Test) TypeNotIN(v ...string) bool {
	return !slices.Contains(v, t.type_)
}

func (t *Test) GetID() uuid.UUID {
	return t.id
}

func (t *Test) GetName() string {
	return t.name
}

func (t *Test) GetCreatedAt() time.Time {
	return t.createdat
}

func (t *Test) GetInfo() *custom_data_type.Custom {
	return t.info
}

func (t *Test) GetInfoValue() custom_data_type.Custom {
	if t.info == nil {
		var zero custom_data_type.Custom
		return zero

	}
	return *t.info
}

func (t *Test) GetType() string {
	return t.type_
}

func (t *Test) GetMetadata() *map[string]any {
	return t.metadata
}

func (t *Test) GetMetadataValue() map[string]any {
	if t.metadata == nil {
		var zero map[string]any
		return zero

	}
	return *t.metadata
}

func (t *Test) SetIDField() {
	if _, exist := t.changedFields[TestTableIDField]; !exist {
		t.changedFields[TestTableIDField] = t.id
		t.changedFieldsList = append(t.changedFieldsList, TestTableIDField)
	}

}
func (t *Test) SetNameField() {
	if _, exist := t.changedFields[TestTableNameField]; !exist {
		t.changedFields[TestTableNameField] = t.name
		t.changedFieldsList = append(t.changedFieldsList, TestTableNameField)
	}

}
func (t *Test) SetCreatedAtField() {
	if _, exist := t.changedFields[TestTableCreatedAtField]; !exist {
		t.changedFields[TestTableCreatedAtField] = t.createdat
		t.changedFieldsList = append(t.changedFieldsList, TestTableCreatedAtField)
	}

}
func (t *Test) SetInfoField() {
	if _, exist := t.changedFields[TestTableInfoField]; !exist {
		t.changedFields[TestTableInfoField] = t.info
		t.changedFieldsList = append(t.changedFieldsList, TestTableInfoField)
	}

}
func (t *Test) SetTypeField() {
	if _, exist := t.changedFields[TestTableTypeField]; !exist {
		t.changedFields[TestTableTypeField] = t.type_
		t.changedFieldsList = append(t.changedFieldsList, TestTableTypeField)
	}

}
func (t *Test) SetMetadataField() {
	if _, exist := t.changedFields[TestTableMetadataField]; !exist {
		t.changedFields[TestTableMetadataField] = t.metadata
		t.changedFieldsList = append(t.changedFieldsList, TestTableMetadataField)
	}

}

func (t *Test) WithDenemeList(opts ...func(*DenemeList)) *client.Relation {
	t.DenemeList = NewRelationDenemeList(t.ctx, t.client.Database)
	for _, opt := range opts {
		opt(t.DenemeList)
	}
	t.result.Deneme = new(DenemeResult)
	t.result.Deneme.Init()
	t.result.relations = append(t.result.relations, t.result.Deneme)
	t.result.relationsMap["deneme"] = t.result.Deneme
	for _, Relation := range t.DenemeList.relations.Relations {
		t.result.Deneme.relations = append(t.result.Deneme.relations, Relation.RelationResult)
		t.result.Deneme.relationsMap[Relation.RelationTable] = Relation.RelationResult
	}
	r := &client.Relation{
		RelationModel:  t.DenemeList,
		RelationTable:  "deneme",
		RelationResult: t.result.Deneme,
		Where:          t.DenemeList.where,

		RelationWhere: &client.RelationCondition{
			RelationValue: "test_id",
			TableValue:    "id",
		},
	}
	t.relations.Relations = append(t.relations.Relations, r)
	t.relations.RelationMap["deneme"] = r
	return r
}

func (t *TestList) WithDenemeList(opts ...func(*DenemeList)) *client.Relation {
	v := NewRelationDenemeList(t.ctx, t.client.Database)
	for _, opt := range opts {
		opt(v)
	}
	t.result.Deneme = new(DenemeResult)
	t.result.Deneme.Init()
	t.result.relations = append(t.result.relations, t.result.Deneme)
	t.result.relationsMap["deneme"] = t.result.Deneme
	for _, Relation := range v.relations.Relations {
		t.result.Deneme.relations = append(t.result.Deneme.relations, Relation.RelationResult)
		t.result.Deneme.relationsMap[Relation.RelationTable] = Relation.RelationResult
	}
	r := &client.Relation{
		RelationModel:  v,
		RelationTable:  "deneme",
		RelationResult: t.result.Deneme,
		Where:          v.where,
		RelationWhere: &client.RelationCondition{
			RelationValue: "test_id",
			TableValue:    "id",
		},
	}
	t.relations.Relations = append(t.relations.Relations, r)
	t.relations.RelationMap["deneme"] = r
	return r
}

func (t *TestList) cleanDenemeList() {
	Relation := t.Items[len(t.Items)-1].relations
	p := 0
	for i, v := range Relation.Relations {
		if v.RelationTable == "deneme" {
			p = i
		}
	}
	Relation.Relations = append(Relation.Relations[:p], Relation.Relations[p+1:]...)
}

func (t *Test) GetChangedFields() map[string]any {
	return t.changedFields
}

func (t *Test) SetDefaults() {
	t.serialFields = nil

	if _, exist := t.changedFields[TestTableIDField]; !exist {
		t.id = uuid.New()
		t.changedFields[TestTableIDField] = t.id
		t.changedFieldsList = append(t.changedFieldsList, TestTableIDField)
	}

}

func (t *Test) SetResult(result client.Result) {
	if t == nil {
		v := NewRelationTest(t.ctx, t.client.Database)
		*t = *v
	}
	t.result = *result.(*TestResult)
}

func (t *TestList) SetResult(result client.Result) {
	if t == nil {
		v := NewRelationTestList(t.ctx, t.client.Database)
		*t = *v
	}
	t.result = *result.(*TestResult)
}

func (t *Test) ScanResult() {
	t.id = t.result.id
	t.name = t.result.name
	t.createdat = t.result.createdat
	t.info = t.result.info
	t.type_ = t.result.type_
	t.metadata = t.result.metadata

	if _, ok := t.relations.RelationMap["deneme"]; ok {
		if t.DenemeList == nil {
			t.DenemeList = NewRelationDenemeList(t.ctx, t.client.Database)
		}
		t.DenemeList.relations = t.relations.RelationMap["deneme"].RelationModel.GetRelationList()
		t.DenemeList.SetResult(t.result.relationsMap["deneme"])
		t.DenemeList.ScanResult()
	}
}

func (t *Test) CheckPrimaryKey(v uuid.UUID) bool {
	return t.id == v
}

func (t *TestList) ScanResult() {
	var v *Test
	if len(t.Items) == 0 {
		v = NewRelationTest(t.ctx, t.client.Database)
		t.Items = append(t.Items, v)
	} else {
		for _, item := range t.Items {
			if item.CheckPrimaryKey(t.result.id) {
				v = item
				break
			}
		}
	}
	if v == nil {
		v = NewRelationTest(t.ctx, t.client.Database)
		t.Items = append(t.Items, v)
	}
	v.result = t.result
	v.relations = t.relations
	v.ScanResult()
}

func (t *Test) GetContext() context.Context {
	return t.ctx
}

func (t *Test) Get() error {
	return databaseTestOperationHook(
		t.ctx,
		client.NewOperationInfo(
			TestTableName,
			client.OperationTypeGet,
		),
		t,
		func() error {
			return t.client.Get(t.ctx, t.where, t, &t.result)
		},
	)
}

func (t *Test) Refresh() error {
	return databaseTestOperationHook(
		t.ctx,
		client.NewOperationInfo(
			TestTableName,
			client.OperationTypeRefresh,
		),
		t,
		func() error {
			return t.client.Refresh(t.ctx, t, &t.result, TestTableIDField, t.id)
		},
	)
}

func (t *Test) Create() error {
	t.SetDefaults()
	return databaseTestOperationHook(
		t.ctx,
		client.NewOperationInfo(
			TestTableName,
			client.OperationTypeCreate,
		),
		t,
		func() error {
			return t.client.Create(t.ctx, TestTableName, t.changedFields, t.changedFieldsList, t.serialFields)
		},
	)
}

func (t *Test) Update() error {
	return databaseTestOperationHook(
		t.ctx,
		client.NewOperationInfo(
			TestTableName,
			client.OperationTypeUpdate,
		),
		t,
		func() error {
			return t.client.Update(t.ctx, TestTableName, t.changedFields, t.changedFieldsList, TestTableIDField, t.id)
		},
	)
}

func (t *Test) Delete() error {
	return databaseTestOperationHook(
		t.ctx,
		client.NewOperationInfo(
			TestTableName,
			client.OperationTypeDelete,
		),
		t,
		func() error {
			return t.client.Delete(t.ctx, TestTableName, TestTableIDField, t.id)
		},
	)
}

func (t *TestList) List() error {
	return databaseTestListOperationHook(
		t.ctx,
		client.NewOperationInfo(
			TestTableName,
			client.OperationTypeList,
		),
		t,
		func() error {
			return t.client.List(t.ctx, t.where, t, &t.result, t.order, t.paging)
		},
	)
}

func (t *TestList) Aggregate(f func(aggregate *client.Aggregate)) (func() error, error) {
	a := new(client.Aggregate)
	f(a)
	return t.client.Aggregate(t.ctx, t.where, t, a)
}

func (t *TestList) AggregateRows(f func(aggregate *client.Aggregate)) (func() error, func(), error) {
	a := new(client.Aggregate)
	f(a)
	return t.client.AggregateRows(t.ctx, t.where, t, a)
}

func (t *TestList) Create(list ...*Test) error {
	return databaseTestListOperationHook(
		t.ctx,
		client.NewOperationInfo(
			TestTableName,
			client.OperationTypeBulkCreate,
		),
		t,
		func() error {
			var changedFieldsList []map[string]any
			var changedFieldsListList [][]string
			for _, item := range list {
				changedFieldsList = append(changedFieldsList, item.changedFields)
				changedFieldsListList = append(changedFieldsListList, item.changedFieldsList)
			}
			return t.client.BulkCreate(t.ctx, TestTableName, changedFieldsList, changedFieldsListList)
		},
	)
}

func (t *TestList) Update(list ...*Test) error {
	return databaseTestListOperationHook(
		t.ctx,
		client.NewOperationInfo(
			TestTableName,
			client.OperationTypeBulkUpdate,
		),
		t,
		func() error {
			var valueList []any
			for _, item := range list {
				valueList = append(valueList, item.id)
			}
			return t.client.BulkUpdate(t.ctx, TestTableName, list[0].changedFields, list[0].changedFieldsList, TestTableIDField, valueList)
		},
	)
}

func (t *TestList) Delete(list ...*Test) error {
	return databaseTestListOperationHook(
		t.ctx,
		client.NewOperationInfo(
			TestTableName,
			client.OperationTypeBulkDelete,
		),
		t,
		func() error {
			var valueList []any
			for _, item := range list {
				valueList = append(valueList, item.id)
			}
			return t.client.BulkDelete(t.ctx, TestTableName, TestTableIDField, valueList)
		},
	)
}

func (t *TestList) DeleteWhere() (int64, error) {
	var affected int64
	err := databaseTestListOperationHook(
		t.ctx,
		client.NewOperationInfo(
			TestTableName,
			client.OperationTypeBulkDelete,
		),
		t,
		func() error {
			var err error
			affected, err = t.client.DeleteWhere(t.ctx, TestTableName, t.where, t, TestTableIDField)
			return err
		},
	)
	return affected, err
}

func (t *TestList) UpdateWhere(set map[string]any) (int64, error) {
	var affected int64
	err := databaseTestListOperationHook(
		t.ctx,
		client.NewOperationInfo(
			TestTableName,
			client.OperationTypeBulkUpdate,
		),
		t,
		func() error {
			var err error
			affected, err = t.client.UpdateWhere(t.ctx, TestTableName, set, t.where, t, TestTableIDField)
			return err
		},
	)
	return affected, err
}

func (t *TestList) Order(field string) *TestList {
	t.order = append(t.order, &client.Order{Field: field})
	return t
}

func (t *TestList) OrderDesc(field string) *TestList {
	t.order = append(t.order, &client.Order{Field: field, Desc: true})
	return t
}

func (t *TestList) Paging(skip, limit int) *TestList {
	t.paging = &client.Paging{Skip: skip, Limit: limit}
	return t
}

type TestResult struct {
	id        uuid.UUID
	name      string
	createdat time.Time
	info      *custom_data_type.Custom
	type_     string
	metadata  *map[string]any

	selectedFields []*client.SelectedField

	Deneme *DenemeResult

	relations    []client.Result
	relationsMap map[string]client.Result
}

func (t *TestResult) Init() {
	t.selectedFields = []*client.SelectedField{}
	t.relationsMap = make(map[string]client.Result)
	t.prepare()
	t.SelectAll()
}

func (t *TestResult) GetSelectedFields() []*client.SelectedField {
	return t.selectedFields
}

func (t *TestResult) GetRelations() []client.Result {
	return t.relations
}

func (t *TestResult) prepare() {
	t.metadata = &map[string]any{}

}

func (t *TestResult) SelectID() {
	v := &client.SelectedField{Name: TestTableIDField, Value: &t.id}
	t.selectedFields = append(t.selectedFields, v)
}

func (t *TestResult) SelectName() {
	v := &client.SelectedField{Name: TestTableNameField, Value: &t.name}
	t.selectedFields = append(t.selectedFields, v)
}

func (t *TestResult) SelectCreatedAt() {
	v := &client.SelectedField{Name: TestTableCreatedAtField, Value: &t.createdat}
	t.selectedFields = append(t.selectedFields, v)
}

func (t *TestResult) SelectInfo() {
	v := &client.SelectedField{Name: TestTableInfoField, Value: &t.info}
	t.selectedFields = append(t.selectedFields, v)
}

func (t *TestResult) SelectType() {
	v := &client.SelectedField{Name: TestTableTypeField, Value: &t.type_}
	t.selectedFields = append(t.selectedFields, v)
}

func (t *TestResult) SelectMetadata() {
	v := &client.SelectedField{Name: TestTableMetadataField, Value: &t.metadata}
	t.selectedFields = append(t.selectedFields, v)
}

func (t *TestResult) GetDBName() string {
	return TestTableName
}

func (t *TestResult) SelectAll() {
	t.SelectID()
	t.SelectName()
	t.SelectCreatedAt()
	t.SelectInfo()
	t.SelectType()
	t.SelectMetadata()

}

func (t *TestResult) IsExist() bool {
	if t == nil {
		return false
	}
	var v uuid.UUID
	return t.id != v
}
