// Code generated by enterprise.
package models

import "github.com/MrSametBurgazoglu/enterprise/client"

import "github.com/google/uuid"
import "time"
import "github.com/MrSametBurgazoglu/enterprise/tests/custom_data_type"
import "strings"

type TestPredicate struct {
	where []*client.WhereList
}

func (t *TestPredicate) Where(w ...client.PredicateI) {
	t.where = nil
	wl := &client.WhereList{}
	wl.Items = append(wl.Items, w...)
	t.where = append(t.where, wl)
}

func (t *TestPredicate) ORWhere(w ...client.PredicateI) {
	wl := &client.WhereList{}
	wl.Items = append(wl.Items, w...)
	t.where = append(t.where, wl)
}

func (t *TestPredicate) IsIDEqual(v uuid.UUID) *client.Where {
	return &client.Where{
		Type:     client.EQ,
		Name:     TestTableIDField,
		HasValue: true,
		Value:    v,
	}
}

func (t *TestPredicate) IsNameEqual(v string) *client.Where {
	return &client.Where{
		Type:     client.EQ,
		Name:     TestTableNameField,
		HasValue: true,
		Value:    v,
	}
}

func (t *TestPredicate) IsCreatedAtEqual(v time.Time) *client.Where {
	return &client.Where{
		Type:     client.EQ,
		Name:     TestTableCreatedAtField,
		HasValue: true,
		Value:    v,
	}
}

func (t *TestPredicate) IsInfoEqual(v custom_data_type.Custom) *client.Where {
	return &client.Where{
		Type:     client.EQ,
		Name:     TestTableInfoField,
		HasValue: true,
		Value:    v,
	}
}

func (t *TestPredicate) IsTypeEqual(v string) *client.Where {
	return &client.Where{
		Type:     client.EQ,
		Name:     TestTableTypeField,
		HasValue: true,
		Value:    v,
	}
}

func (t *TestPredicate) IsMetadataEqual(v map[string]any) *client.Where {
	return &client.Where{
		Type:     client.EQ,
		Name:     TestTableMetadataField,
		HasValue: true,
		Value:    v,
	}
}

func (t *TestPredicate) IsIDNotEqual(v uuid.UUID) *client.Where {
	return &client.Where{
		Type:     client.NEQ,
		Name:     TestTableIDField,
		HasValue: true,
		Value:    v,
	}
}

func (t *TestPredicate) IsNameNotEqual(v string) *client.Where {
	return &client.Where{
		Type:     client.NEQ,
		Name:     TestTableNameField,
		HasValue: true,
		Value:    v,
	}
}

func (t *TestPredicate) IsCreatedAtNotEqual(v time.Time) *client.Where {
	return &client.Where{
		Type:     client.NEQ,
		Name:     TestTableCreatedAtField,
		HasValue: true,
		Value:    v,
	}
}

func (t *TestPredicate) IsInfoNotEqual(v custom_data_type.Custom) *client.Where {
	return &client.Where{
		Type:     client.NEQ,
		Name:     TestTableInfoField,
		HasValue: true,
		Value:    v,
	}
}

func (t *TestPredicate) IsTypeNotEqual(v string) *client.Where {
	return &client.Where{
		Type:     client.NEQ,
		Name:     TestTableTypeField,
		HasValue: true,
		Value:    v,
	}
}

func (t *TestPredicate) IsMetadataNotEqual(v map[string]any) *client.Where {
	return &client.Where{
		Type:     client.NEQ,
		Name:     TestTableMetadataField,
		HasValue: true,
		Value:    v,
	}
}

func (t *TestPredicate) IsIDIN(v ...uuid.UUID) *client.Where {
	return &client.Where{
		Type:     client.ANY,
		Name:     TestTableIDField,
		HasValue: true,
		Value:    v,
	}
}

func (t *TestPredicate) IsNameIN(v ...string) *client.Where {
	return &client.Where{
		Type:     client.ANY,
		Name:     TestTableNameField,
		HasValue: true,
		Value:    v,
	}
}

func (t *TestPredicate) IsCreatedAtIN(v ...time.Time) *client.Where {
	return &client.Where{
		Type:     client.ANY,
		Name:     TestTableCreatedAtField,
		HasValue: true,
		Value:    v,
	}
}

func (t *TestPredicate) IsInfoIN(v ...custom_data_type.Custom) *client.Where {
	return &client.Where{
		Type:     client.ANY,
		Name:     TestTableInfoField,
		HasValue: true,
		Value:    v,
	}
}

func (t *TestPredicate) IsTypeIN(v ...string) *client.Where {
	return &client.Where{
		Type:     client.ANY,
		Name:     TestTableTypeField,
		HasValue: true,
		Value:    v,
	}
}

func (t *TestPredicate) IsMetadataIN(v ...map[string]any) *client.Where {
	return &client.Where{
		Type:     client.ANY,
		Name:     TestTableMetadataField,
		HasValue: true,
		Value:    v,
	}
}

func (t *TestPredicate) IsIDNotIN(v ...uuid.UUID) *client.Where {
	return &client.Where{
		Type:     client.NANY,
		Name:     TestTableIDField,
		HasValue: true,
		Value:    v,
	}
}

func (t *TestPredicate) IsNameNotIN(v ...string) *client.Where {
	return &client.Where{
		Type:     client.NANY,
		Name:     TestTableNameField,
		HasValue: true,
		Value:    v,
	}
}

func (t *TestPredicate) IsCreatedAtNotIN(v ...time.Time) *client.Where {
	return &client.Where{
		Type:     client.NANY,
		Name:     TestTableCreatedAtField,
		HasValue: true,
		Value:    v,
	}
}

func (t *TestPredicate) IsInfoNotIN(v ...custom_data_type.Custom) *client.Where {
	return &client.Where{
		Type:     client.NANY,
		Name:     TestTableInfoField,
		HasValue: true,
		Value:    v,
	}
}

func (t *TestPredicate) IsTypeNotIN(v ...string) *client.Where {
	return &client.Where{
		Type:     client.NANY,
		Name:     TestTableTypeField,
		HasValue: true,
		Value:    v,
	}
}

func (t *TestPredicate) IsMetadataNotIN(v ...map[string]any) *client.Where {
	return &client.Where{
		Type:     client.NANY,
		Name:     TestTableMetadataField,
		HasValue: true,
		Value:    v,
	}
}

func (t *TestPredicate) IsNameLike(v string) *client.Where {
	return &client.Where{
		Type:     client.LIKE,
		Name:     TestTableNameField,
		HasValue: true,
		Value:    v,
	}
}

func (t *TestPredicate) IsNameILike(v string) *client.Where {
	return &client.Where{
		Type:     client.ILIKE,
		Name:     TestTableNameField,
		HasValue: true,
		Value:    v,
	}
}

func (t *TestPredicate) IsTypeLike(v string) *client.Where {
	return &client.Where{
		Type:     client.LIKE,
		Name:     TestTableTypeField,
		HasValue: true,
		Value:    v,
	}
}

func (t *TestPredicate) IsTypeILike(v string) *client.Where {
	return &client.Where{
		Type:     client.ILIKE,
		Name:     TestTableTypeField,
		HasValue: true,
		Value:    v,
	}
}

func (t *TestPredicate) IsInfoNil() *client.Where {
	return &client.Where{
		Type: client.NIL,
		Name: TestTableInfoField,
	}
}

func (t *TestPredicate) IsMetadataNil() *client.Where {
	return &client.Where{
		Type: client.NIL,
		Name: TestTableMetadataField,
	}
}

func (t *TestPredicate) IsInfoNotNil() *client.Where {
	return &client.Where{
		Type: client.NNIL,
		Name: TestTableInfoField,
	}
}

func (t *TestPredicate) IsMetadataNotNil() *client.Where {
	return &client.Where{
		Type: client.NNIL,
		Name: TestTableMetadataField,
	}
}

func (t *TestPredicate) CreatedAtGreaterThan(v time.Time) *client.Where {
	return &client.Where{
		Type:     client.GT,
		Name:     TestTableCreatedAtField,
		HasValue: true,
		Value:    v,
	}
}

func (t *TestPredicate) CreatedAtGreaterEqualThan(v time.Time) *client.Where {
	return &client.Where{
		Type:     client.GTE,
		Name:     TestTableCreatedAtField,
		HasValue: true,
		Value:    v,
	}
}

func (t *TestPredicate) CreatedAtLowerThan(v time.Time) *client.Where {
	return &client.Where{
		Type:     client.LT,
		Name:     TestTableCreatedAtField,
		HasValue: true,
		Value:    v,
	}
}

func (t *TestPredicate) CreatedAtLowerEqualThan(v time.Time) *client.Where {
	return &client.Where{
		Type:     client.LTE,
		Name:     TestTableCreatedAtField,
		HasValue: true,
		Value:    v,
	}
}

func (t *TestPredicate) GetWhereInfoString() string {
	var whereString []string
	for _, list := range t.where {
		whereAnd := ""
		var whereAndString []string
		for _, item := range list.Items {
			whereAndString = append(whereAndString, item.GetName())
		}
		whereAnd = strings.Join(whereAndString, "_AND_")
		whereString = append(whereString, whereAnd)
	}
	return strings.Join(whereString, "__OR__")
}
